/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, SBAssistantEducationAlertItem;

@interface SBAssistantEducationAlertManager : XXUnknownSuperclass {
	int _notifyToken;
	id _unlockHandler;
	NSTimer* _unlockTimer;
	BOOL _waitingOnUserDataSync;
	SBAssistantEducationAlertItem* _item;
}
+(BOOL)isUserEducated;
+(void)setUserHasBeenEducated;
+(void)pleaseEducateTheUserWhenYouGetAChance;
-(id)init;
-(void)dealloc;
-(void)_invalidate;
-(void)_showEducationAlertIfPossible;
-(void)_startUnlockTimer;
-(void)_clearUnlockTimer;
-(void)_unlockTimerFired:(id)fired;
-(void)educationAlertWasDeactivated:(id)deactivated;
@end

