/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, UIButton;

@interface SBAwayLockBar : XXUnknownSuperclass {
	UIButton* _slideshowButton;
	UIButton* _cameraButton;
	NSMutableDictionary* _orientationToButtonImages;
}
-(void)dealloc;
-(void)setShowsSlideshowButton:(BOOL)button;
-(void)setSlideshowButtonSelected:(BOOL)selected;
-(void)setShowsCameraButton:(BOOL)button;
-(void)setOrientation:(int)orientation;
-(id)_newButtonWithAction:(SEL)action tag:(int)tag hasComposedImage:(BOOL)image;
-(id)_unselectedImageForButtonTag:(int)buttonTag interfaceOrientation:(int)orientation;
-(id)_selectedImageForButtonTag:(int)buttonTag interfaceOrientation:(int)orientation;
-(void)_setImagesForButton:(id)button orientation:(int)orientation;
-(void)_setShowsButton:(BOOL)button button:(id*)button2 buttonTag:(int)tag hasComposedImage:(BOOL)image action:(SEL)action animated:(BOOL)animated;
-(void)_slideshowButtonActivated:(id)activated;
-(void)_cameraButtonHit:(id)hit;
@end

