/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"


@interface SBCalendarApplicationIcon : SBApplicationIcon {
}
-(id)initWithApplication:(id)application;
-(void)dealloc;
-(void)localeChanged;
-(id)generateIconImage:(int)image;
-(BOOL)canGenerateGhostlyImageInBackground;
@end

